config/routes.rb
Rails.application.routes.draw do
  resources :files, only: [:index, :create]

  namespace :dashboard do
    resources :lines
    resources :stops, only: [:index, :create]
    get 'stops/:name' => 'stops#show', as: 'stop_name'
    resources :stops, only: [:index, :create, :show]
    resources :toilets, only: [:index, :create, :update, :destroy]

    resources :feedbacks, only: [:index, :destroy]
  end

  resources :logs, only: [:index, :create]

  get 'dashboard' => 'dashboard#index'
  get 'about' => 'home#about', as: 'about'
  root 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => 'sessions#new'
  # resources :users, only: [:new, :create]
  # get 'register' => 'users#new'

  get 'lines/:name' => 'lines#show', as: 'line_name'
  resources :lines, only: [:index]

  get 'stops/:name' => 'stops#show', as: 'stop_name'

  resources :feedbacks, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  has_attached_file :file
  validates_attachment :file,
                       presence: true,
                       content_type: {content_type: /image\/.*/}
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  validates :content, presence: true
end

app/models/line.rb
class Line < ApplicationRecord
  has_many :stops, dependent: :destroy
  has_many :toilets, dependent: :destroy
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :line
  has_many :toilets, dependent: :destroy
end

app/models/toilet.rb
class Toilet < ApplicationRecord
  belongs_to :stop
  belongs_to :line
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create}, uniqueness: {case_sensitive: false}, allow_blank: true
  validates :password, presence: true, length: {minimum: 6}
  has_secure_password

  has_many :logs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_log_in
    unless helpers.logged_in?
      flash[:warning] = "please log in first"

      session[:redirect_to] = request.url
      redirect_to login_path
    end
  end
end

app/controllers/dashboard/lines_controller.rb
class Dashboard::LinesController < DashboardController
  def index
    @lines = Line.all
  end

  def create
    @line = Line.new(params.require(:line).permit(:name))

    if @line.save
      redirect_to dashboard_lines_path
    end
  end

  def show
    line_id = params[:id]
    @line = Line.find_by(id: line_id)
    @lines = Line.all

    @stops = @line.stops
  end

  def edit
  end

  def update
  end

  def destroy
    @line = Line.find(params[:id])

    if @line.destroy
      redirect_to dashboard_lines_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_log_in

  def index
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def new
  end

  def create
    title = nil || params[:title]
    @feedback = Feedback.new(params[:feedback].permit(:contact, :content))
    @feedback.title = title

    if verify_rucaptcha?(@feedback) && @feedback.save
      flash[:success] = '谢谢您的反馈'
    else
      flash[:warning] = '反馈提交失败'
    end

    redirect_to new_feedback_path
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @files = Attachment.all
  end

  # upload single file using name: file
  # upload multiple files using name: files[]
  def create
    unless params[:file].nil?
      @file = create_file(params[:file])
    end

    unless params[:files].nil?
      @files = []
      params[:files].each do |file|
        @files << create_file(file)
      end
    end

    render :show
  end

  def show
  end

  private
    def create_file(raw_file)
      Attachment.create(file: raw_file)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @toilets = Toilet.all
  end

  def about
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lines = Line.all
  end


  def show
    line_name = params[:name]
    @line = Line.find_by(name: line_name)

    helpers.not_found unless @line

    @lines = Line.all
    @stops = @line.stops
    @stop = Stop.new
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :require_log_in, only: [:create]

  def index
    @logs = Log.all.order(created_at: :desc)
  end

  def create
    @log = Log.new(params.require(:log).permit(:title, :content))
    @log.user = helpers.current_user

    if @log.save
      redirect_to logs_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_log_in, only: [:destroy]

  def new
    if helpers.logged_in?
      redirect_to dashboard_path
    end
  end

  def create
    redirect_to_path = session[:redirect_to]
    name = params[:user][:name]
    password = params[:user][:password]

    @user = User.find_by(name: name)

    if @user && @user.authenticate(password)
      helpers.log_in
      flash[:success] = 'u have logged in'

      if redirect_to_path.present?
        session.delete(:redirect_to)
        redirect_to redirect_to_path
      else
        redirect_to dashboard_path
      end

    else
      flash[:warning] = 'name or password wrong'
      redirect_to login_path
    end
  end

  def destroy
    helpers.log_out
    redirect_to login_path
  end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  def index
    @stops = Stop.all
  end

  def show
    @stop_name = params[:name]
    @lines = helpers.lines_of_stop(@stop_name)
    @toilets = helpers.toilets_of_stop(@stop_name)
  end
end

app/controllers/toilets_controller.rb
class ToiletsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :password))

    if @user.save
      helpers.log_in

      flash[:success] = "Register successfully"
      redirect_to dashboard_path
    else
      flash[:warning] = "Register fails"
      redirect_to register_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = "")
    t = "上海地铁站内厕所索引"
    title.blank? ? t : "#{title} - #{t}"
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/helpers/lines_helper.rb
module LinesHelper
  include StopsHelper
  def say_hi
    "Hello world"
  end

  def get_stop_name(stop)
    @stop_name = stop.name
  end

  def get_stops_from_stop_name(stop_name)
    @stops = Stop.where(name: stop_name)

    # 404
    not_found if @stops.empty?
  end

  def lines_of_stop(stop_name)
    get_stops_from_stop_name(stop_name)
    @lines = @stops.map {|stop| stop.line }
  end

  def toilets_of_stop(stop_name)
    get_stops_from_stop_name(stop_name)
    @toilets = @stops.map {|stop| stop.toilets}.compact.flatten
  end

  def stop_has_toilets?(stop)
    get_stop_name(stop)
    toilets_of_stop(@stop_name).empty?
  end

  def stop_has_toilets_at_other_line?(stop)
    get_stop_name(stop)
    all_toilets = toilets_of_stop(@stop_name)
    stop_toilets = stop.toilets

    if special_stop?(@stop_name)
      # SPECIAL_STOPS 不通，若通便是换乘站，所以一直返回 true
      true
    else
      (all_toilets - stop_toilets).empty?
    end
  end

  # 可换乘的line
  def exchangeable_lines(stop)
    get_stop_name(stop)
    if special_stop?(@stop_name)
      []
    else
      lines_of_stop(@stop_name) - [stop.line]
    end

    # return @lines, array
  end

  def exchange_stop?(stop)
    get_stop_name(stop)
    if special_stop?(@stop_name)
      false
    else
      (lines_of_stop(@stop_name).count > 1)
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in
    session[:current_user_id] = @user.id
  end

  def current_user
    @current_user = User.find_by(id: session[:current_user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:current_user_id)
    @current_user = nil
  end
end

app/helpers/stops_helper.rb
module StopsHelper
  SPECIAL_STOPS = %w(浦电路)

  def special_stop?(stop_name)
    SPECIAL_STOPS.include? stop_name
  end
end

app/views/lines/index.html.erb
<ul class="list-group">
  <% @lines.each do |line| %>
      <a href=<%= line_name_path(line.name)%> class="list-group-item" >
        <span style="border-left: 6pt solid <%= line.mark_color %>;
            border-radius: 4pt;
            margin-right: 6pt;"></span>
        <span class="badge"><%= "共 #{line.stops.count} 站" %></span>
        <%= "#{line.name} 号线" %>
      </a>
  <% end %>
</ul>

app/views/lines/show.html.erb
<% content_for :title, "#{@line.name}号线" %>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>符号</th>
    <th>含义</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>
            <span class="font-large">
              <%= link_to("上海地铁", '#') %>
            </span>
    </td>
    <td>
      该线 站内有厕所
    </td>
  </tr>
  <tr>
    <td>
      <span class="font-tiny">上海地铁</span>
    </td>
    <td>
      无重要信息
    </td>
  </tr>
  <tr>
    <td>
      <%= fa_icon('exchange') %>
          <span class="font-tiny">
            <%= link_to("上海地铁", '#') %>
          </span>
    </td>
    <td>
      需要换乘到其他线 站内有厕所
    </td>
  </tr>
  <tr>
    <td>
      <%= fa_icon 'refresh' %>
      (
      <span class="font-tiny">
      <%= link_to '1号线', '#' %>
      <%= link_to '2号线', '#' %>
      </span>
      )
    </td>
    <td>
      换乘站 可换乘
    </td>
  </tr>
  </tbody>
</table>

<h1 style="border-bottom: 4pt solid <%= @line.mark_color %>"><%= @line.name %>号线</h1>

<ul>
  <% @stops.each do |stop| %>
      <li>
        <p>

          <% unless stop.toilets.empty? %>
            <span class="font-large">
              <%= link_to("#{stop.name}", stop_name_path(stop.name)) %>
            </span>
          <% else %>
            <% unless stop_has_toilets_at_other_line?(stop) %>
              <%= fa_icon('exchange') %>
              <span class="font-tiny">
              <%= link_to("#{stop.name}", stop_name_path(stop.name)) %>
              </span>
            <% else %>
              <span class="font-tiny">
                <%= stop.name %>
              </span>
            <% end %>
          <% end %>

          <% if exchange_stop?(stop) %>
              <%= fa_icon 'refresh' %>
              (
              <% exchangeable_lines(stop).each do |line| %>
                <span class="font-tiny">
                <%= link_to "#{line.name}号线", line_name_path(line.name) %>
                </span>
              <% end %>
              )
          <% end %>
        </p>

      </li>
  <% end %>
</ul>