config/routes.rb
Rails.application.routes.draw do
  resources :files, only: [:index, :create]

  namespace :dashboard do
    resources :lines
    resources :stops, only: [:index, :create]
    get 'stops/:name' => 'stops#show', as: 'stop_name'
    resources :stops, only: [:index, :create, :show]
    resources :toilets, only: [:index, :create, :update, :destroy]

    resources :feedbacks, only: [:index, :destroy]
  end

  resources :logs, only: [:index, :create]

  get 'dashboard' => 'dashboard#index'
  get 'about' => 'home#about', as: 'about'
  root 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => 'sessions#new'
  # resources :users, only: [:new, :create]
  # get 'register' => 'users#new'

  get 'lines/:name' => 'lines#show', as: 'line_name'
  resources :lines, only: [:index]

  get 'stops/:name' => 'stops#show', as: 'stop_name'

  resources :feedbacks, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line.rb
class Line < ApplicationRecord
  has_many :stops, dependent: :destroy
  has_many :toilets, dependent: :destroy
end

app/controllers/dashboard/feedbacks_controller.rb
class Dashboard::FeedbacksController < DashboardController
  def index
    @feedbacks = Feedback.all.order(created_at: :desc)
  end

  def destroy
    @feedback = Feedback.find(params[:id])

    if @feedback.destroy
      flash[:success] = 'feedback destroy successfully'
      redirect_to dashboard_feedbacks_path
    end
  end
end

app/controllers/dashboard/lines_controller.rb
class Dashboard::LinesController < DashboardController
  def index
    @lines = Line.all
  end

  def create
    @line = Line.new(params.require(:line).permit(:name))

    if @line.save
      redirect_to dashboard_lines_path
    end
  end

  def show
    line_id = params[:id]
    @line = Line.find_by(id: line_id)
    @lines = Line.all

    @stops = @line.stops
  end

  def edit
  end

  def update
  end

  def destroy
    @line = Line.find(params[:id])

    if @line.destroy
      redirect_to dashboard_lines_path
    end
  end
end

app/controllers/dashboard/stops_controller.rb
class Dashboard::StopsController < DashboardController
  def index
  end

  def create
    line_id = params[:line][:id]

    @stop = Stop.new(params.require(:stop).permit(:name))
    @stop.line = Line.find(line_id)

    if @stop.save
      redirect_to dashboard_line_path(line_id)
    end
  end

  def show
    @stop_name = params[:name]
    @lines = helpers.lines_of_stop(@stop_name)
    @toilets = helpers.toilets_of_stop(@stop_name)
  end
end

app/controllers/dashboard/toilets_controller.rb
class Dashboard::ToiletsController < DashboardController
  def index
    @toilets = Toilet.all
  end

  def create
    stop_name = params[:stop_name]
    line_id = params[:line_id]
    stop_id = Line.find_by(id: line_id).stops.select {|stop| stop.name.eql? stop_name}.first.id

    @toilet = Toilet.new(
        description: params[:toilet][:description],
        stop_id: stop_id,
        line_id: params[:line_id]
    )

    if @toilet.save
      redirect_to :back
    end
  end

  def destroy
    @toilet = Toilet.find(params[:id])
    if @toilet.destroy
      flash[:success] = "destroy #{@toilet.description} success"
      redirect_to dashboard_toilets_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_log_in

  def index
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lines = Line.all
  end


  def show
    line_name = params[:name]
    @line = Line.find_by(name: line_name)

    helpers.not_found unless @line

    @lines = Line.all
    @stops = @line.stops
    @stop = Stop.new
  end
end

app/helpers/lines_helper.rb
module LinesHelper
  include StopsHelper
  def say_hi
    "Hello world"
  end

  def get_stop_name(stop)
    @stop_name = stop.name
  end

  def get_stops_from_stop_name(stop_name)
    @stops = Stop.where(name: stop_name)

    # 404
    not_found if @stops.empty?
  end

  def lines_of_stop(stop_name)
    get_stops_from_stop_name(stop_name)
    @lines = @stops.map {|stop| stop.line }
  end

  def toilets_of_stop(stop_name)
    get_stops_from_stop_name(stop_name)
    @toilets = @stops.map {|stop| stop.toilets}.compact.flatten
  end

  def stop_has_toilets?(stop)
    get_stop_name(stop)
    toilets_of_stop(@stop_name).empty?
  end

  def stop_has_toilets_at_other_line?(stop)
    get_stop_name(stop)
    all_toilets = toilets_of_stop(@stop_name)
    stop_toilets = stop.toilets

    if special_stop?(@stop_name)
      # SPECIAL_STOPS 不通，若通便是换乘站，所以一直返回 true
      true
    else
      (all_toilets - stop_toilets).empty?
    end
  end

  # 可换乘的line
  def exchangeable_lines(stop)
    get_stop_name(stop)
    if special_stop?(@stop_name)
      []
    else
      lines_of_stop(@stop_name) - [stop.line]
    end

    # return @lines, array
  end

  def exchange_stop?(stop)
    get_stop_name(stop)
    if special_stop?(@stop_name)
      false
    else
      (lines_of_stop(@stop_name).count > 1)
    end
  end

end

app/views/dashboard/lines/index.html.erb
<h1>上海地铁 Lines</h1>

<ul>

  <% @lines.each do |line| %>
    <li>
      <%= link_to( "#{line.name}号线", dashboard_line_path(line)) %>
      <%= link_to fa_icon('trash'), dashboard_line_path(line), method: :delete, data: {confirm: 'are u sure?'} %>
    </li>
  <% end %>
</ul>


<%= form_for :line, url: dashboard_lines_path do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/dashboard/lines/show.html.erb
<%= link_to 'All lines', dashboard_lines_path %>
<h1>Line: <%= @line.name %></h1>

<ul>
  <% @stops.each do |stop| %>
      <li>
        <p>
          <%= fa_icon('exchange') if exchange_stop?(stop) %>
          <% unless stop.toilets.empty? %>
            <span style="font-size: 20px;">
              <%= link_to("#{stop.name}", dashboard_stop_name_path(stop.name)) %>
            </span>
          <% else %>
              <%= fa_icon('home') unless stop_has_toilets_at_other_line?(stop) %>
              <span style="font-size: 10px; margin: auto;">
              <%= link_to("#{stop.name}", dashboard_stop_name_path(stop.name)) %>
            </span>
          <% end %>
        </p>

      </li>
  <% end %>
</ul>

<p>可以创建 站</p>

<%= form_for :stop, url: dashboard_stops_path do |f| %>
    <%= hidden_field :line, :id %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>