config/routes.rb
Rails.application.routes.draw do
  resources :files, only: [:index, :create]

  namespace :dashboard do
    resources :lines
    resources :stops, only: [:index, :create]
    get 'stops/:name' => 'stops#show', as: 'stop_name'
    resources :stops, only: [:index, :create, :show]
    resources :toilets, only: [:index, :create, :update, :destroy]

    resources :feedbacks, only: [:index, :destroy]
  end

  resources :logs, only: [:index, :create]

  get 'dashboard' => 'dashboard#index'
  get 'about' => 'home#about', as: 'about'
  root 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => 'sessions#new'
  # resources :users, only: [:new, :create]
  # get 'register' => 'users#new'

  get 'lines/:name' => 'lines#show', as: 'line_name'
  resources :lines, only: [:index]

  get 'stops/:name' => 'stops#show', as: 'stop_name'

  resources :feedbacks, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/toilet.rb
class Toilet < ApplicationRecord
  belongs_to :stop
  belongs_to :line
end

app/controllers/dashboard/feedbacks_controller.rb
class Dashboard::FeedbacksController < DashboardController
  def index
    @feedbacks = Feedback.all.order(created_at: :desc)
  end

  def destroy
    @feedback = Feedback.find(params[:id])

    if @feedback.destroy
      flash[:success] = 'feedback destroy successfully'
      redirect_to dashboard_feedbacks_path
    end
  end
end

app/controllers/dashboard/lines_controller.rb
class Dashboard::LinesController < DashboardController
  def index
    @lines = Line.all
  end

  def create
    @line = Line.new(params.require(:line).permit(:name))

    if @line.save
      redirect_to dashboard_lines_path
    end
  end

  def show
    line_id = params[:id]
    @line = Line.find_by(id: line_id)
    @lines = Line.all

    @stops = @line.stops
  end

  def edit
  end

  def update
  end

  def destroy
    @line = Line.find(params[:id])

    if @line.destroy
      redirect_to dashboard_lines_path
    end
  end
end

app/controllers/dashboard/stops_controller.rb
class Dashboard::StopsController < DashboardController
  def index
  end

  def create
    line_id = params[:line][:id]

    @stop = Stop.new(params.require(:stop).permit(:name))
    @stop.line = Line.find(line_id)

    if @stop.save
      redirect_to dashboard_line_path(line_id)
    end
  end

  def show
    @stop_name = params[:name]
    @lines = helpers.lines_of_stop(@stop_name)
    @toilets = helpers.toilets_of_stop(@stop_name)
  end
end

app/controllers/dashboard/toilets_controller.rb
class Dashboard::ToiletsController < DashboardController
  def index
    @toilets = Toilet.all
  end

  def create
    stop_name = params[:stop_name]
    line_id = params[:line_id]
    stop_id = Line.find_by(id: line_id).stops.select {|stop| stop.name.eql? stop_name}.first.id

    @toilet = Toilet.new(
        description: params[:toilet][:description],
        stop_id: stop_id,
        line_id: params[:line_id]
    )

    if @toilet.save
      redirect_to :back
    end
  end

  def destroy
    @toilet = Toilet.find(params[:id])
    if @toilet.destroy
      flash[:success] = "destroy #{@toilet.description} success"
      redirect_to dashboard_toilets_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_log_in

  def index
  end
end

app/controllers/toilets_controller.rb
class ToiletsController < ApplicationController
  def index
  end
end

app/views/dashboard/toilets/index.html.erb
<h1>All Toilets</h1>



<%= form_for :log, url: logs_path do |f| %>
    <div class="form-group">
      <label for="">Title</label>
      <%= text_field_tag 'log[title]', value = "#{Time.now.strftime("%Y-%m-%d %H:%M")}", class: 'form-control' %>
    </div>
    <div class="form-group">
      <label for="">Content</label>
      <%= f.text_area :content, class: 'form-control toilet-textarea' %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Line</th>
      <th>Stop</th>
      <th>Stop ID</th>
      <th>Description</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @toilets.each_with_index do |toilet, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td><%= toilet.line.name %></td>
          <td><%= toilet.stop.name %></td>
          <td><%= toilet.stop_id %></td>
          <td><%= toilet.description %></td>
          <td><%= link_to fa_icon('edit'), '#' %></td>
          <td><%= link_to fa_icon('trash-o'), dashboard_toilet_path(toilet.id), method: :delete, data: {confirm: 'are u sure?'} %></td>
        </tr>
    <% end %>
  </tbody>
</table>